* Minutes
** <2014-11-13 Thu 15:00-15:30>
[Topics]
- Mario breifly explain about the project to our new member Marti (Hi Marti!)
- We discuss the possibility of organizing workshops in order to get some financing for the group
- Marti tells us about his current work in SPECS and his minibot robotic platform
- Mario and Quim bring some material for the hacklab and we activate the borrow/return system for the group.
- We plan the work for the next week

[Decisions]
- Until the lockers are in place the material will be borrowed/returned through the normal library system
- Marti lends a arduino health kit to Nil for continuing his work on EMG signal recording
- Quim will continue to print the parts of the hand
- Mario will buy the missing servos and try to get some more electronic material
- David will build a new finger start kit
- Guillem and Joan will work on the hands as soon as the parts get printed

Next meeting will be on Tue 18th 12:30
** <2014-11-07 Fri 17:00-18:30>
Attendance: 6 persons
It is espected two new incorporations.
Remember that participation is open to everyone!

[Decisions]
- The meetings will be weekly. All members come and discuss general topics for 30 min.
- Pedro asumes role of "technical secretary": minutes, comunication, blabla.

[Tasks]
- Investigate on assembly of finger's prototype (with servo motors) [Joan]
- Request lockers to store material in hacklab [Aurelio/Marcel]
- Buy servo motor [Mario]
- Blog, organization, organize the group [Pedro]
- Request computer 100% autonomous [Pedro]
- Github for ROBOT group [Pedro]
- Upload photo of brainstorming [Mario]

Next meeting have to be decided:
http://doodle.com/av9z3957yscez5ia

[Media]
- Brainstorm photo (missing)
- [[https://docs.google.com/uc?id=0B6rX6PgzeBdyT1doUFdBZWVtaFE&export=download][finger sensor]]
- [[https://docs.google.com/uc?id=0B6rX6PgzeBdybXhUMkZqanZ3bjQ&export=download][finger potentiometer]]
- [[https://docs.google.com/uc?id=0B6rX6PgzeBdyd0ppWWN6RXZlS0E&export=download][finger matlab]]
- [[https://docs.google.com/uc?id=0B6rX6PgzeBdyZXI2MVhxVC1QT0E&export=download][emg test]]
** The initial idea in the mailing list
Construct this robot consisting on 3d printable pieces and arduino logic:
http://www.inmoov.fr/gallery/

Schemes:
- http://www.inmoov.fr/download/
- https://www.wevolver.com/gael.langevin/inmoov-robot/network

Let's start with the fingers!
http://www.thingiverse.com/thing:17773
